---
apiVersion: v1
kind: Service
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: beginner.codes-soc
        tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
    annotations:
        kubernetes.io/ingress.class: "traefik-external"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
    tls:
      - hosts:
        - soc.beginner.codes
        secretName: beginner.codes-soc-cert
    rules:
      - host: soc.beginner.codes
        http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                    service:
                        name: summer-of-code
                        port:
                            number: 8000
