---
apiVersion: v1
kind: Service
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: beginner.codes-soc
        tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/limit-rpm: "100"
        cert-manager.io/cluster-issuer: "letsencrypt"
spec:
    tls:
      - hosts:
        - soc.beginner.codes
        secretName: beginner.codes-soc-cert
    rules:
      - host: soc.beginner.codes
        http:
            paths:
              - backend:
                    serviceName: summer-of-code
                    servicePort: 8000
