"""Allow for larger emoji names

Revision ID: 21a923931b8c
Revises: 90c2c1e28da2
Create Date: 2022-07-24 15:59:39.744059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21a923931b8c"
down_revision = "90c2c1e28da2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
