"""Create tables

Revision ID: 224cc0554906
Revises: 
Create Date: 2022-06-26 18:30:48.558142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "224cc0554906"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column("avatar", sa.Unicode(length=256), nullable=True),
        sa.Column("email", sa.Unicode(length=256), nullable=False),
        sa.Column("password", sa.Unicode(length=256), nullable=False),
        sa.Column(
            "joined",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "Roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Unicode(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Roles")
    op.drop_table("Users")
    # ### end Alembic commands ###
