"""Create tables

Revision ID: 564536bb6ac9
Revises: 
Create Date: 2022-05-29 10:51:01.814789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "564536bb6ac9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=64), nullable=False),
        sa.Column("avatar", sa.Text(length=256), nullable=True),
        sa.Column("email", sa.Text(length=256), nullable=False),
        sa.Column(
            "joined",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Unicode(length=512), nullable=False),
        sa.Column("description", sa.Unicode(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SessionFields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Unicode(length=8192), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["Sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(length=32), nullable=False),
        sa.Column("link", sa.Unicode(length=512), nullable=False),
        sa.Column("description", sa.Unicode(length=4096), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("challenge_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenge_id"], ["Challenges.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SubmissionStatus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(length=32), nullable=False),
        sa.Column(
            "updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["Submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.Unicode(length=12), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submission", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission"], ["Submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Votes")
    op.drop_table("SubmissionStatus")
    op.drop_table("Submissions")
    op.drop_table("SessionFields")
    op.drop_table("Sessions")
    op.drop_table("Roles")
    op.drop_table("Challenges")
    op.drop_table("Users")
    # ### end Alembic commands ###
