"""(actually) Allow for larger emoji names

Revision ID: 71deb111e3f9
Revises: 21a923931b8c
Create Date: 2022-07-24 16:29:45.060785

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71deb111e3f9"
down_revision = "21a923931b8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Votes", "emoji", type_=sa.Unicode(128))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Votes", "emoji", type_=sa.Unicode(12))
    # ### end Alembic commands ###
