"""Create tables the rest of the tables

Revision ID: 90c2c1e28da2
Revises: 224cc0554906
Create Date: 2022-07-03 15:25:32.787994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90c2c1e28da2"
down_revision = "224cc0554906"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Unicode(length=512), nullable=False),
        sa.Column("description", sa.Unicode(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("values", sa.Unicode(length=4096), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Unicode(length=32), nullable=False),
        sa.Column("link", sa.Unicode(length=512), nullable=False),
        sa.Column("description", sa.Unicode(length=4096), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("challenge_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenge_id"], ["Challenges.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SubmissionStatusModel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Unicode(length=32), nullable=False),
        sa.Column(
            "updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["Submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.Unicode(length=12), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("submission", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission"], ["Submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Votes")
    op.drop_table("SubmissionStatusModel")
    op.drop_table("Submissions")
    op.drop_table("Sessions")
    op.drop_table("Challenges")
    # ### end Alembic commands ###
