"""Add settings table

Revision ID: df6f2bf16b39
Revises: 71deb111e3f9
Create Date: 2022-07-28 16:20:56.477183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df6f2bf16b39"
down_revision = "71deb111e3f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=256), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Settings")
    # ### end Alembic commands ###
